"""Minimal type stub for the `pypdfium2` surface `weft_pdf.pdf_layout` calls.

`pypdfium2` ships no `py.typed` marker (checked directly: the installed distribution has none),
which strict pyright refuses at the `import` line under `reportMissingTypeStubs`. `pdfplumber`
and `pypdf`, this pack's other two third-party dependencies, both ship their own inline types and
need nothing here. This follows the precedent `typings/rouge_score` and `typings/bert_score`
already set for the same problem against two other untyped libraries: a stub covering only the
calls actually made, not a full re-statement of the library's surface.
"""

from PIL.Image import Image

class PdfBitmap:
    def to_pil(self) -> Image: ...

class PdfPage:
    def render(self, scale: float = ...) -> PdfBitmap: ...

class PdfDocument:
    def __init__(self, input: bytes, password: str | None = ..., autoclose: bool = ...) -> None: ...
    def __getitem__(self, index: int) -> PdfPage: ...
    def __len__(self) -> int: ...
    def __enter__(self) -> PdfDocument: ...
    def __exit__(self, *exc: object) -> None: ...
    def close(self) -> None: ...
