"""Open RAGBench as a corpus this repository can pin — Phase 38 task **38.3**.

`vectara/open_ragbench` labels each question against a section of one of its own processed arXiv
documents, so those documents are the corpus the question set is judged against. They are not
tracked here: `corpus/open-ragbench.toml` is, and `fetch_corpus.py` materialises it. Each entry pins
two things, the way a Wikipedia revision is pinned — the JSON the dataset serves at a fixed commit
(`source_sha256`) and the markdown this module writes from it (`sha256`) — so a changed dataset and
a changed rendering fail differently.

**The rendering keeps every section's text exactly as the dataset wrote it.** A question's quote is
the opening span of its gold section, and a span is verified by finding it literally in the stored
document; any normalisation here would be a second copy of the text that the quote no longer
matches. The title leads, whitespace-collapsed because the dataset wraps it; tables follow the
section that holds them; figures are base64 data URIs and are dropped, counted in `images_dropped`.

`manifest` writes the manifest from a local copy of the dataset. It hashes what is on disk and names
the pinned URL each file is served at, so the pins can be checked against the network by
`fetch_corpus.py fetch` without a local copy, and against a local copy with `--source-dir`.

**Task 38.8 adds a second corpus over the same dataset: the raw PDFs it was built from.** They are
not rendered — a PDF stays a PDF — so they need no `render` or `source_sha256` pin, only the plain
one every `fetch` document carries. `stage_pdfs` links the ones that are usable into a directory of
their own (they are 3.2 GB; a copy would double that for no reason), and `pdf_manifest_text` writes
a manifest over that directory so `fetch_corpus.py` and an experiment's corpus loader see it exactly
as they see any other corpus — an exclusion still names itself in the manifest, so a document this
repository chose not to carry is a recorded decision rather than a silent gap.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import sys
from collections.abc import Mapping
from dataclasses import dataclass
from enum import StrEnum
from pathlib import Path
from typing import Final

#: A fixed Hugging Face commit of `vectara/open_ragbench`, so no file named below can change under a
#: manifest pinned to it.
RAGBENCH_REVISION: Final[str] = "63f6b052ff83508b08e242db42263ee708815c26"
RAGBENCH_REPO_URL: Final[str] = "https://huggingface.co/datasets/vectara/open_ragbench"

#: The dataset files a question set is built from, pinned beside the documents.
DATASET_FILES: Final[tuple[str, ...]] = (
    "queries.json",
    "qrels.json",
    "answers.json",
    "pdf_urls.json",
)

CORPUS_NAME: Final[str] = "open-ragbench-arxiv"

#: Where rendered documents land, relative to the manifest's own directory.
DOCUMENT_DIRECTORY: Final[str] = "open-ragbench"

#: The name of the raw-PDF corpus (38.8), distinct from `CORPUS_NAME`'s rendered one.
PDF_CORPUS_NAME: Final[str] = "open-ragbench-arxiv-pdf"


class OpenRagbenchRendering(StrEnum):
    """The one shape a processed Open RAGBench document is written in."""

    MARKDOWN = "open-ragbench-md"


@dataclass(frozen=True)
class RenderedDocument:
    """One rendered document, and how many figures rendering dropped from it."""

    text: str
    images_dropped: int


def ragbench_file_url(name: str) -> str:
    """The pinned URL of a file under the dataset's `pdf/arxiv/` directory."""
    return f"{RAGBENCH_REPO_URL}/resolve/{RAGBENCH_REVISION}/pdf/arxiv/{name}"


def render_document(body: bytes) -> RenderedDocument:
    """One processed document's JSON, as the markdown the corpus stores."""
    document = json.loads(body)
    parts = [f"# {' '.join(str(document['title']).split())}"]
    images_dropped = 0
    for section in document["sections"]:
        parts.append(str(section["text"]).strip("\n"))
        parts.extend(str(table).strip("\n") for table in section["tables"].values())
        images_dropped += len(section["images"])
    return RenderedDocument(text="\n\n".join(parts) + "\n", images_dropped=images_dropped)


def _sha256(body: bytes) -> str:
    return hashlib.sha256(body).hexdigest()


def manifest_text(dataset: Path) -> str:
    """The manifest for the dataset copy at `dataset`, a directory in the dataset's `pdf/arxiv/`
    layout: one `[[document]]` per `corpus/*.json`, sorted by id, and one `[[dataset_file]]` per
    file in `DATASET_FILES`."""
    lines = [
        "# The Open RAGBench corpus — Phase 38 task 38.3. Generated by `scripts/open_ragbench.py`",
        "# manifest; edit the script, not this file. Materialise with",
        "# `python scripts/fetch_corpus.py fetch --manifest corpus/open-ragbench.toml`.",
        "",
        "[corpus]",
        f'name = "{CORPUS_NAME}"',
        "",
        "[dataset]",
        f'repository = "{RAGBENCH_REPO_URL}"',
        f'revision = "{RAGBENCH_REVISION}"',
    ]
    for name in DATASET_FILES:
        lines += [
            "",
            "[[dataset_file]]",
            f'name = "{name}"',
            f'source = "{ragbench_file_url(name)}"',
            f'sha256 = "{_sha256((dataset / name).read_bytes())}"',
        ]
    for path in sorted((dataset / "corpus").glob("*.json")):
        body = path.read_bytes()
        rendered = render_document(body)
        identifier = path.stem
        lines += [
            "",
            "[[document]]",
            f'id = "{identifier}"',
            f'path = "{DOCUMENT_DIRECTORY}/{identifier}.md"',
            'format = "md"',
            'language = "en"',
            'tier = "fetch"',
            f'source = "{ragbench_file_url(f"corpus/{identifier}.json")}"',
            f'source_sha256 = "{_sha256(body)}"',
            f'render = "{OpenRagbenchRendering.MARKDOWN.value}"',
            f"images_dropped = {rendered.images_dropped}",
            f'sha256 = "{_sha256(rendered.text.encode("utf-8"))}"',
        ]
    return "\n".join(lines) + "\n"


def stage_pdfs(pdfs: Path, stage: Path, *, excluded: Mapping[str, str]) -> tuple[str, ...]:
    """Links every `*.pdf` under `pdfs` into `stage`, skipping the excluded ids.

    A link, not a copy: the dataset's PDFs are 3.2 GB, and staging is a view over files that
    already exist on disk, not a second copy of them. Re-staging replaces an existing link, so this
    is safe to run again after `pdfs` changes.
    """
    stage.mkdir(parents=True, exist_ok=True)
    staged: list[str] = []
    for source in sorted(pdfs.glob("*.pdf")):
        identifier = source.stem
        if identifier in excluded:
            continue
        link = stage / f"{identifier}.pdf"
        if link.is_symlink() or link.exists():
            link.unlink()
        link.symlink_to(source.resolve())
        staged.append(identifier)
    return tuple(sorted(staged))


def pdf_manifest_text(stage: Path, *, manifest_dir: Path, excluded: Mapping[str, str]) -> str:
    """The manifest for the staged PDFs at `stage`: one `[[document]]` per staged link, sorted by
    id, pinned by its arXiv version URL and the sha256 of the bytes the link resolves to. Every
    excluded id is named with its reason, so a document this script chose not to carry is stated
    rather than silently missing."""
    lines = [
        "# The Open RAGBench raw-PDF corpus — Phase 38 task 38.8. Generated by",
        "# `scripts/open_ragbench.py pdf-manifest`; edit the script, not this file.",
        "# The corpus is the dataset's raw arXiv PDFs.",
    ]
    for identifier, reason in sorted(excluded.items()):
        lines.append(f"# excluded {identifier}: {reason}")
    lines += [
        "",
        "[corpus]",
        f'name = "{PDF_CORPUS_NAME}"',
    ]
    for path in sorted(stage.glob("*.pdf")):
        identifier = path.stem
        relative = Path(os.path.relpath(path, manifest_dir)).as_posix()
        lines += [
            "",
            "[[document]]",
            f'id = "{identifier}"',
            f'path = "{relative}"',
            'format = "pdf"',
            'language = "en"',
            'tier = "fetch"',
            f'source = "https://arxiv.org/pdf/{identifier}"',
            f'sha256 = "{_sha256(path.read_bytes())}"',
        ]
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    subcommands = parser.add_subparsers(dest="action", required=True)
    manifest = subcommands.add_parser(
        "manifest", help="write the corpus manifest from a local copy"
    )
    manifest.add_argument("--dataset", type=Path, required=True)
    manifest.add_argument("--out", type=Path, required=True)
    pdf_manifest = subcommands.add_parser(
        "pdf-manifest", help="stage the raw PDFs as links and write their manifest"
    )
    pdf_manifest.add_argument("--pdfs", type=Path, required=True)
    pdf_manifest.add_argument("--stage", type=Path, required=True)
    pdf_manifest.add_argument("--out", type=Path, required=True)
    pdf_manifest.add_argument(
        "--exclude",
        action="append",
        default=[],
        metavar="ID=REASON",
        help="an id to leave out of staging, with its reason. Repeatable.",
    )
    arguments = parser.parse_args(argv)

    if arguments.action == "pdf-manifest":
        excluded = dict(item.split("=", 1) for item in arguments.exclude)
        staged = stage_pdfs(arguments.pdfs, arguments.stage, excluded=excluded)
        arguments.out.write_text(
            pdf_manifest_text(
                arguments.stage, manifest_dir=arguments.out.parent, excluded=excluded
            ),
            encoding="utf-8",
        )
        print(f"wrote {arguments.out}: {len(staged)} documents, {len(excluded)} excluded")
        return 0

    arguments.out.write_text(manifest_text(arguments.dataset), encoding="utf-8")
    print(f"wrote {arguments.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
