"""Open RAGBench as a corpus this repository can pin — Phase 38 task **38.3**.

`vectara/open_ragbench` labels each question against a section of one of its own processed arXiv
documents, so those documents are the corpus the question set is judged against. They are not
tracked here: `corpus/open-ragbench.toml` is, and `fetch_corpus.py` materialises it. Each entry pins
two things, the way a Wikipedia revision is pinned — the JSON the dataset serves at a fixed commit
(`source_sha256`) and the markdown this module writes from it (`sha256`) — so a changed dataset and
a changed rendering fail differently.

**The rendering keeps every section's text exactly as the dataset wrote it.** A question's quote is
the opening span of its gold section, and a span is verified by finding it literally in the stored
document; any normalisation here would be a second copy of the text that the quote no longer
matches. The title leads, whitespace-collapsed because the dataset wraps it; tables follow the
section that holds them; figures are base64 data URIs and are dropped, counted in `images_dropped`.

`manifest` writes the manifest from a local copy of the dataset. It hashes what is on disk and names
the pinned URL each file is served at, so the pins can be checked against the network by
`fetch_corpus.py fetch` without a local copy, and against a local copy with `--source-dir`.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from dataclasses import dataclass
from enum import StrEnum
from pathlib import Path
from typing import Final

#: A fixed Hugging Face commit of `vectara/open_ragbench`, so no file named below can change under a
#: manifest pinned to it.
RAGBENCH_REVISION: Final[str] = "63f6b052ff83508b08e242db42263ee708815c26"
RAGBENCH_REPO_URL: Final[str] = "https://huggingface.co/datasets/vectara/open_ragbench"

#: The dataset files a question set is built from, pinned beside the documents.
DATASET_FILES: Final[tuple[str, ...]] = (
    "queries.json",
    "qrels.json",
    "answers.json",
    "pdf_urls.json",
)

CORPUS_NAME: Final[str] = "open-ragbench-arxiv"

#: Where rendered documents land, relative to the manifest's own directory.
DOCUMENT_DIRECTORY: Final[str] = "open-ragbench"


class OpenRagbenchRendering(StrEnum):
    """The one shape a processed Open RAGBench document is written in."""

    MARKDOWN = "open-ragbench-md"


@dataclass(frozen=True)
class RenderedDocument:
    """One rendered document, and how many figures rendering dropped from it."""

    text: str
    images_dropped: int


def ragbench_file_url(name: str) -> str:
    """The pinned URL of a file under the dataset's `pdf/arxiv/` directory."""
    return f"{RAGBENCH_REPO_URL}/resolve/{RAGBENCH_REVISION}/pdf/arxiv/{name}"


def render_document(body: bytes) -> RenderedDocument:
    """One processed document's JSON, as the markdown the corpus stores."""
    document = json.loads(body)
    parts = [f"# {' '.join(str(document['title']).split())}"]
    images_dropped = 0
    for section in document["sections"]:
        parts.append(str(section["text"]).strip("\n"))
        parts.extend(str(table).strip("\n") for table in section["tables"].values())
        images_dropped += len(section["images"])
    return RenderedDocument(text="\n\n".join(parts) + "\n", images_dropped=images_dropped)


def _sha256(body: bytes) -> str:
    return hashlib.sha256(body).hexdigest()


def manifest_text(dataset: Path) -> str:
    """The manifest for the dataset copy at `dataset`, a directory in the dataset's `pdf/arxiv/`
    layout: one `[[document]]` per `corpus/*.json`, sorted by id, and one `[[dataset_file]]` per
    file in `DATASET_FILES`."""
    lines = [
        "# The Open RAGBench corpus — Phase 38 task 38.3. Generated by `scripts/open_ragbench.py`",
        "# manifest; edit the script, not this file. Materialise with",
        "# `python scripts/fetch_corpus.py fetch --manifest corpus/open-ragbench.toml`.",
        "",
        "[corpus]",
        f'name = "{CORPUS_NAME}"',
        "",
        "[dataset]",
        f'repository = "{RAGBENCH_REPO_URL}"',
        f'revision = "{RAGBENCH_REVISION}"',
    ]
    for name in DATASET_FILES:
        lines += [
            "",
            "[[dataset_file]]",
            f'name = "{name}"',
            f'source = "{ragbench_file_url(name)}"',
            f'sha256 = "{_sha256((dataset / name).read_bytes())}"',
        ]
    for path in sorted((dataset / "corpus").glob("*.json")):
        body = path.read_bytes()
        rendered = render_document(body)
        identifier = path.stem
        lines += [
            "",
            "[[document]]",
            f'id = "{identifier}"',
            f'path = "{DOCUMENT_DIRECTORY}/{identifier}.md"',
            'format = "md"',
            'language = "en"',
            'tier = "fetch"',
            f'source = "{ragbench_file_url(f"corpus/{identifier}.json")}"',
            f'source_sha256 = "{_sha256(body)}"',
            f'render = "{OpenRagbenchRendering.MARKDOWN.value}"',
            f"images_dropped = {rendered.images_dropped}",
            f'sha256 = "{_sha256(rendered.text.encode("utf-8"))}"',
        ]
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    subcommands = parser.add_subparsers(dest="action", required=True)
    manifest = subcommands.add_parser(
        "manifest", help="write the corpus manifest from a local copy"
    )
    manifest.add_argument("--dataset", type=Path, required=True)
    manifest.add_argument("--out", type=Path, required=True)
    arguments = parser.parse_args(argv)

    arguments.out.write_text(manifest_text(arguments.dataset), encoding="utf-8")
    print(f"wrote {arguments.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
