"""`scripts/replay_all.py` — task **44.50a**, E0a: replays every committed multi-arm experiment.

Generates `eval/replay/README.md`'s content (the dispatching session writes the file): for each
`<experiments>/*.toml` document with at least two arms, `weft_eval.replay.replay` on the
document's first declared metric, over every run record found anywhere under `root` in a
directory named `runs`. An arm whose query pipeline reads labels at query time is a control, not
a choice a router could make, and is excluded before replay. An experiment that cannot be
replayed is named with the refusal, never dropped.
"""

from __future__ import annotations

import argparse
from collections.abc import Sequence
from pathlib import Path
from typing import Final

from weft_cli.pipeline_catalogue import load_pipeline_document
from weft_eval.evidence import AmbiguousInvocationError, IncompleteExperimentError
from weft_eval.experiment import Experiment, ExperimentArm, load_experiment
from weft_eval.falsify import UnpairableRecordsError
from weft_eval.replay import (
    ReplayRow,
    ReplayTable,
    UnscoredMetricError,
    render_replay_table,
    replay,
)
from weft_eval.run_record import RunRecord, load_run_record

#: The two plugins of the test-only `weft-oracle-anchors` pack that read a labels file at query
#: time — an arm whose query pipeline uses one of these is a control, not a choice a router could
#: make.
LABEL_READING_PLUGINS: Final[frozenset[str]] = frozenset(
    {"oracle-anchor-promote", "oracle-gold-first"}
)

_REFUSALS = (
    UnpairableRecordsError,
    IncompleteExperimentError,
    AmbiguousInvocationError,
    UnscoredMetricError,
)


def _reads_labels_at_query_time(experiments: Path, arm: ExperimentArm) -> bool:
    """Whether `arm`'s query pipeline document has a stage using a label-reading plugin."""
    if arm.query_pipeline is None:
        return False
    path = experiments / "pipelines" / f"{arm.query_pipeline}.yaml"
    if not path.is_file():
        return False
    pipeline = load_pipeline_document(path)
    return any(stage.use in LABEL_READING_PLUGINS for stage in pipeline.stages)


def _control_arm_names(experiments: Path, experiment: Experiment) -> list[str]:
    return [arm.name for arm in experiment.arms if _reads_labels_at_query_time(experiments, arm)]


def _headline_cell(row: ReplayRow | None) -> str:
    """`row`'s delta as the headline table's cell — see the module's own README preamble."""
    if row is None or row.delta is None:
        return "—"
    if row.delta.low is None or row.delta.high is None:
        return f"— ({row.delta.mean:+.3f})"
    return f"{row.delta.low:+.3f} to {row.delta.high:+.3f} ({row.delta.mean:+.3f})"


def _headline_row(table: ReplayTable) -> str:
    by_label = {row.label: row for row in table.rows}
    oracle = by_label["oracle"]
    self_oracle = by_label.get("self-oracle")
    return (
        f"| {table.experiment} | {table.metric} | {oracle.n} | {_headline_cell(oracle)} | "
        f"{_headline_cell(self_oracle)} |"
    )


def _replayed_section(table: ReplayTable) -> list[str]:
    return render_replay_table(table).splitlines()[2:]


def _replay_one(
    experiments: Path, records: Sequence[RunRecord], experiment: Experiment
) -> tuple[list[str], str | None]:
    """One experiment's section, and its headline row when it replayed."""
    excluded = _control_arm_names(experiments, experiment)
    kept = tuple(arm for arm in experiment.arms if arm.name not in excluded)
    lines = [f"## {experiment.name}", ""]
    if excluded:
        lines.append(
            f"excluded: {', '.join(repr(name) for name in excluded)} — reads labels at query time"
        )
        lines.append("")
    if len(kept) < 2:
        lines.append("skipped: fewer than two arms a router could choose between")
        return lines, None
    replayed = experiment.model_copy(update={"arms": kept})
    try:
        table = replay(replayed, records, metric=replayed.metrics[0])
    except _REFUSALS as exc:
        lines.append(f"skipped: {exc}")
        return lines, None
    lines.extend(_replayed_section(table))
    return lines, _headline_row(table)


_HEADER = [
    "# E0a — per-question headroom over every committed multi-arm experiment",
    "",
    "Generated by `uv run python scripts/replay_all.py`; do not edit. Each section is `weft "
    "eval replay` on the document's first declared metric, over every record under `eval/` "
    "whose digest matches the document. An arm whose query pipeline reads labels at query "
    "time is a control a router cannot choose, and is left out.",
    "",
    "| experiment | metric | n | oracle − best | self-oracle − best |",
    "|---|---|---|---|---|",
]


def replay_report(experiments: Path, root: Path) -> str:
    r"""Replay every `<experiments>/*.toml` document with at least two arms, sorted by filename.

    Every run record found anywhere under `root` in a directory named `runs`
    (`root.glob("**/runs/*.json")`) is passed to every experiment: `replay` itself matches
    records to a document by digest. Ends in exactly one `\n`.
    """
    if not experiments.is_dir():
        raise FileNotFoundError(f"no experiments directory at '{experiments}' — it is missing")
    records = [load_run_record(path) for path in sorted(root.glob("**/runs/*.json"))]
    headline_rows: list[str] = []
    sections: list[list[str]] = []
    for path in sorted(experiments.glob("*.toml")):
        experiment = load_experiment(path)
        if len(experiment.arms) < 2:
            continue
        section, headline = _replay_one(experiments, records, experiment)
        sections.append(section)
        if headline is not None:
            headline_rows.append(headline)

    lines = [*_HEADER, *headline_rows]
    for section in sections:
        lines.append("")
        lines.extend(section)
    return "\n".join(lines) + "\n"


def main(argv: Sequence[str] | None = None) -> int:
    """Print `replay_report` over `--experiments`/`--root`.

    Args:
        argv: The command-line arguments; `None` reads `sys.argv`.

    Returns:
        The process exit code.
    """
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--experiments", type=Path, default=Path("eval/experiments"))
    parser.add_argument("--root", type=Path, default=Path("eval"))
    args = parser.parse_args(argv)
    print(replay_report(args.experiments, args.root), end="", flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
