"""A pinned RFC corpus — Phase 39 task **39.3**.

Modelled on `scripts/open_ragbench.py`: the bytes are not tracked, `corpus/rfc.toml` pins each
document's sha256, and `scripts/fetch_corpus.py fetch` materialises it from that manifest. An RFC is
served as-is by the RFC Editor — plain text, already the shape a corpus wants — so there is no
`render` and no `source_sha256` here, unlike Open RAGBench's JSON-to-markdown step: the file stored
is the file served.

**The owner's rule Q2, and why this module checks it rather than trusting the question author**: a
question's anchor is only evidence of intent-matching when exact string matching cannot win on it by
construction, which requires the anchor to occur in at least two documents of the corpus. A question
set that satisfied Q2 only in the author's head would be untested the moment a document changed, so
`check-questions` reads the corpus text itself and reports every anchor that fails the count, every
anchor the question text does not itself contain, and every quote absent from its own relevant
document — the three ways a question can claim evidence it does not have.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
import tomllib
import urllib.error
import urllib.request
from collections.abc import Mapping, Sequence
from pathlib import Path
from typing import Final

from pydantic import BaseModel, ConfigDict

RFC_EDITOR_URL: Final[str] = "https://www.rfc-editor.org/rfc/rfc{number}.txt"
CORPUS_NAME: Final[str] = "rfc"
#: Where documents live, relative to the manifest's own directory, and where `download` and
#: `check-questions` read `rfc*.txt` from.
DOCUMENT_DIRECTORY: Final[str] = "rfc"
#: Identifies this script to the RFC Editor, which otherwise sees an anonymous client.
USER_AGENT: Final[str] = (
    "weft-corpus/1.0 (https://github.com/AdamKrysztopa/weft; corpus materialisation)"
)

_FILENAME: Final[re.Pattern[str]] = re.compile(r"rfc(\d+)\.txt")


def rfc_url(number: int) -> str:
    """The RFC Editor's plain-text URL for RFC `number`."""
    return RFC_EDITOR_URL.format(number=number)


def _rfc_number(path: Path) -> int:
    """The RFC number `path` names, or a refusal naming the file that does not fit the pattern."""
    match = _FILENAME.fullmatch(path.name)
    if match is None:
        message = f"{path} is not named rfc<number>.txt, so it is not part of the pinned corpus."
        raise ValueError(message)
    return int(match.group(1))


def manifest_text(documents: Path) -> str:
    """Render the manifest for the RFC texts in `documents`.

    One `[[document]]` per `rfc*.txt`, sorted by RFC number, pinning the sha256 of the file exactly
    as the RFC Editor serves it.
    """
    lines = [
        "# The RFC corpus — Phase 39 task 39.3. Generated by `scripts/rfc_corpus.py` manifest;",
        "# edit the script, not this file. Materialise with",
        "# `python scripts/fetch_corpus.py fetch --manifest corpus/rfc.toml`.",
        "",
        "[corpus]",
        f'name = "{CORPUS_NAME}"',
    ]
    for path in sorted(documents.glob("rfc*.txt"), key=_rfc_number):
        number = _rfc_number(path)
        identifier = f"rfc{number}"
        body = path.read_bytes()
        lines += [
            "",
            "[[document]]",
            f'id = "{identifier}"',
            f'path = "{DOCUMENT_DIRECTORY}/{identifier}.txt"',
            'format = "txt"',
            'language = "en"',
            'tier = "fetch"',
            f'source = "{rfc_url(number)}"',
            f'sha256 = "{hashlib.sha256(body).hexdigest()}"',
        ]
    return "\n".join(lines) + "\n"


def anchor_document_frequency(anchor: str, texts: Mapping[str, str]) -> int:
    """How many of `texts` contain `anchor` as a whole token.

    Case-sensitive, and not touching an ASCII letter, digit or underscore on either side, so `"42"`
    does not match inside `"429"`.
    """
    pattern = re.compile(rf"(?<![A-Za-z0-9_]){re.escape(anchor)}(?![A-Za-z0-9_])")
    return sum(1 for text in texts.values() if pattern.search(text))


class RfcQuestion(BaseModel):
    """One question against the RFC corpus, as a `[[question]]` table declares it."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    id: str
    text: str
    relevant_document: str
    quote: str
    #: The literal strings a retriever could match on directly, checked by Q2 against the corpus
    #: rather than trusted from whoever wrote the question.
    anchors: tuple[str, ...] = ()


def question_problems(question: RfcQuestion, texts: Mapping[str, str]) -> list[str]:
    """Every way `question` fails to be sound against `texts`, each a sentence naming its id.

    Checked in order: the relevant document exists; its quote occurs there verbatim; each anchor
    occurs in the question's own text; each anchor is not a construction win — it occurs in at
    least two documents (Q2). A sound question returns `[]`.
    """
    problems: list[str] = []
    document_text = texts.get(question.relevant_document)
    if document_text is None:
        problems.append(
            f"{question.id}: relevant document {question.relevant_document!r} is not in the corpus."
        )
    elif question.quote not in document_text:
        problems.append(
            f"{question.id}: quote {question.quote!r} does not occur verbatim in "
            f"{question.relevant_document}."
        )

    for anchor in question.anchors:
        if anchor not in question.text:
            problems.append(
                f"{question.id}: anchor {anchor!r} does not occur in the question's own text."
            )

    for anchor in question.anchors:
        frequency = anchor_document_frequency(anchor, texts)
        if frequency < 2:
            noun = "document" if frequency == 1 else "documents"
            problems.append(
                f"{question.id}: anchor {anchor!r} occurs in {frequency} {noun}, fewer than the "
                "two Q2 requires so exact matching would win on it by construction."
            )
    return problems


def _toml_string(value: str) -> str:
    """A TOML basic string: JSON's escapes are a subset of TOML's."""
    return json.dumps(value, ensure_ascii=False)


def _split(questions: Sequence[RfcQuestion], *, seed: str) -> dict[str, str]:
    """Assign `train` to the first half of each anchor slice in a seeded hash order, `test` after.

    So fusion weights are fitted on one half of each slice and reported on the other (G24).
    """
    splits: dict[str, str] = {}
    for anchored in (True, False):
        members = sorted(
            (q.id for q in questions if bool(q.anchors) is anchored),
            key=lambda identifier: hashlib.sha256(f"{seed}:{identifier}".encode()).hexdigest(),
        )
        half = len(members) // 2
        for index, identifier in enumerate(members):
            splits[identifier] = "train" if index < half else "test"
    return splits


def question_set_text(questions: Sequence[RfcQuestion], *, seed: str = "39.3") -> str:
    """Render `questions` as a Weft question set, schema 2, sorted by id.

    It carries an `anchored` axis and a `split` axis halving each anchored slice; the anchors
    themselves are recorded in `notes`.
    """
    splits = _split(questions, seed=seed)
    lines = [
        "# Phase 39's RFC questions — ledger task 39.3. Generated by `scripts/rfc_corpus.py`",
        "# questions; edit the source question files and regenerate, never this file.",
        "",
        "[question_set]",
        "schema = 2",
        'absent = ["kind", "difficulty", "reference_answer"]',
        'absent_reason = "Written to judge retrieval: each question names the one RFC that '
        'answers it and quotes it, and states no answer, kind or difficulty nobody checked"',
        'axes = ["anchored", "split"]',
    ]
    for question in sorted(questions, key=lambda q: q.id):
        notes = "anchors: " + ", ".join(question.anchors) if question.anchors else "no anchor"
        anchored = "yes" if question.anchors else "no"
        lines += [
            "",
            "[[question]]",
            f"id = {_toml_string(question.id)}",
            f"text = {_toml_string(question.text)}",
            'language = "en"',
            f"relevant_documents = [{_toml_string(question.relevant_document)}]",
            f"notes = {_toml_string(notes)}",
            f'axes = {{ anchored = "{anchored}", split = "{splits[question.id]}" }}',
            "",
            "  [[question.quote]]",
            f"  document = {_toml_string(question.relevant_document)}",
            "  page = 0",
            f"  text = {_toml_string(question.quote)}",
        ]
    return "\n".join(lines) + "\n"


def _load_texts(documents: Path) -> dict[str, str]:
    texts: dict[str, str] = {}
    for path in sorted(documents.glob("rfc*.txt")):
        # RFC text is nominally ASCII, but `errors="replace"` tolerates the odd non-ASCII byte in
        # an older RFC rather than failing the whole corpus load over one character.
        texts[path.stem] = path.read_text(encoding="utf-8", errors="replace")
    return texts


def _load_questions(path: Path) -> list[RfcQuestion]:
    with path.open("rb") as handle:
        raw = tomllib.load(handle)
    return [RfcQuestion(**entry) for entry in raw.get("question", [])]


def _download(numbers_file: Path, into: Path) -> int:
    with numbers_file.open("rb") as handle:
        raw = tomllib.load(handle)
    numbers = [int(number) for number in raw["numbers"]]
    into.mkdir(parents=True, exist_ok=True)
    for number in numbers:
        identifier = f"rfc{number}"
        destination = into / f"{identifier}.txt"
        if destination.is_file():
            print(f"present {identifier}")
            continue
        url = rfc_url(number)
        if not url.startswith("https://"):
            message = f"{identifier}: refusing to fetch a non-https url: {url!r}"
            raise ValueError(message)
        request = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})  # noqa: S310
        try:
            # noqa S310 below: the scheme is checked immediately above, which is the audit S310
            # asks for. The URL is built from a pinned template, not user input.
            with urllib.request.urlopen(request, timeout=60) as response:  # noqa: S310
                body = response.read()
        except urllib.error.HTTPError as exc:
            message = f"{identifier}: fetching {url} returned HTTP {exc.code}"
            raise RuntimeError(message) from exc
        destination.write_bytes(body)
        print(f"fetched {identifier} ({len(body)} bytes)")
    return 0


def _write_manifest(documents: Path, out: Path) -> None:
    out.write_text(manifest_text(documents), encoding="utf-8")
    print(f"wrote {out}")


def _check_questions(questions_path: Path, documents: Path) -> int:
    questions = _load_questions(questions_path)
    texts = _load_texts(documents)
    problems: list[str] = []
    for question in questions:
        problems.extend(question_problems(question, texts))
    for problem in problems:
        print(problem)
    print(f"{len(questions)} questions, {len(problems)} problems")
    return 1 if problems else 0


def main(argv: list[str] | None = None) -> int:
    """Download, pin, check or convert the RFC corpus and its question set.

    Args:
        argv: The command-line arguments; `None` reads `sys.argv`.

    Returns:
        The process exit code.
    """
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    subcommands = parser.add_subparsers(dest="action", required=True)

    download = subcommands.add_parser(
        "download", help="fetch each RFC named in a numbers file, skipping what is already present"
    )
    download.add_argument("--numbers-file", type=Path, required=True)
    download.add_argument("--into", type=Path, required=True)

    manifest = subcommands.add_parser("manifest", help="write the corpus manifest")
    manifest.add_argument("--documents", type=Path, required=True)
    manifest.add_argument("--out", type=Path, required=True)

    check = subcommands.add_parser(
        "check-questions", help="check a question set's quotes and anchors against the corpus text"
    )
    check.add_argument("--questions", type=Path, required=True)
    check.add_argument("--documents", type=Path, required=True)

    convert = subcommands.add_parser(
        "questions", help="write the Weft question set from checked source question files"
    )
    convert.add_argument("--source", type=Path, nargs="+", required=True)
    convert.add_argument("--out", type=Path, required=True)

    arguments = parser.parse_args(argv)

    if arguments.action == "download":
        try:
            return _download(arguments.numbers_file, arguments.into)
        except RuntimeError as exc:
            print(f"error: {exc}", file=sys.stderr)
            return 1
    if arguments.action == "manifest":
        _write_manifest(arguments.documents, arguments.out)
        return 0
    if arguments.action == "questions":
        sources = [question for path in arguments.source for question in _load_questions(path)]
        arguments.out.write_text(question_set_text(sources), encoding="utf-8")
        print(f"wrote {arguments.out}: {len(sources)} questions")
        return 0
    return _check_questions(arguments.questions, arguments.documents)


if __name__ == "__main__":
    sys.exit(main())
